### ISSUE TITLE
Filter news updates related to player stats

### ISSUE THREAD

**Issue by CpuKnows** [CpuKnows/fantasy-nlg#1]
There are possibly many news items during a week, but only one game per week.

We want to only use news updates that contain a summary of a player's stats for a game.

Players may have no update or 1 update for a game. A news update on a game day doesn't necessarily contain player stats but an update posted after the game finishes probably does.

**Comment by vaibhavsingh007** [comment]
I took a look at the Rotowire and Pro-football. 
Can you share links to a match stat, by players, and the corresponding news articles? 
Further questions then will be, do we actually implement scraping or simply prepare the data manually, for the scope of this project. 
Data preparation strategy pending discussion..

**Comment by CpuKnows** [comment]
Commit #6b74f5e filters news updates to game day. Still need to filter unrelated game day news updates.
