### ISSUE TITLE
Filter players at certain posisitions

### ISSUE THREAD

**Issue by CpuKnows** [CpuKnows/fantasy-nlg#2]
We just want to look at player stats and news updates at positions:

- Quarterback (QB)
- Running back (RB)
- Wide Receiver (WR)
- Tight End (TE)

We may evaluate kickers later.

**Comment by vaibhavsingh007** [comment]
Right, so for creating tags, we will have to group by aspects (types). Eg. ones shared here (QB, RB..) are 'player position' aspects?
